artifacts:
  artifacts_dir: artifacts
  pickle_format_data_dir: pickle_format_data
  img_pickle_file_name: img_pickle_file.pkl
  pickle_actor_names : actor_names.pkl
  cropped_dir: __Cropped_data
  feature_extraction_dir: extracted_features
  extracted_features_name: embedding.pkl
  upload_image_dir: upload